#!/usr/bin/env bash
#
# changes-to-patch.sh — turn uncommitted git changes into a phpatcher ed-script
# bundle.
#
# For every file that differs from the base revision it emits:
#
#     # file: <path-relative-to-repo-root>
#     <output of `diff -e <base version> <working-tree version>`>
#
# Because it uses `diff -e` (ed script), the patch contains only line numbers and
# the new text — never the original/removed lines.
#
# Usage:
#   tools/changes-to-patch.sh                       # all changes -> stdout
#   tools/changes-to-patch.sh -o my.patch           # ... -> file
#   tools/changes-to-patch.sh src/A.php src/B.php   # only these files
#   tools/changes-to-patch.sh -b HEAD~3             # diff against another base
#
# Notes:
#   * Run it from inside the git repository whose changes you want to capture.
#   * Explicit file arguments must be given relative to the repository root.
#   * Set phpatcher.base_dir to the repository root so the "# file:" paths
#     resolve to the right files on disk.
#   * Added (brand-new) and deleted files are skipped: phpatcher patches files
#     that already exist on disk, so those cases are not representable.

set -euo pipefail

BASE="HEAD"
OUT=""

usage() {
    cat <<'EOF'
Usage:
  tools/changes-to-patch.sh                       # all changes -> stdout
  tools/changes-to-patch.sh -o my.patch           # ... -> file
  tools/changes-to-patch.sh src/A.php src/B.php   # only these files
  tools/changes-to-patch.sh -b HEAD~3             # diff against another base

Options:
  -b, --base <rev>      base revision to diff against (default: HEAD)
  -o, --output <file>   write the bundle to <file> instead of stdout
  -h, --help            show this help
EOF
}

die() { echo "$@" >&2; exit 1; }

while [[ $# -gt 0 ]]; do
    case "$1" in
        -b|--base)   BASE="${2:?missing value for $1}"; shift 2 ;;
        -o|--output) OUT="${2:?missing value for $1}"; shift 2 ;;
        -h|--help)   usage; exit 0 ;;
        --)          shift; break ;;
        -*)          die "Unknown option: $1" ;;
        *)           break ;;
    esac
done

# Remaining positional arguments are explicit file paths to capture.
args=("$@")

command -v git >/dev/null 2>&1 || die "git not found"

repo_root="$(git rev-parse --show-toplevel 2>/dev/null)" \
    || die "Not a git repository (run this from inside the project)."

git -C "$repo_root" rev-parse --verify --quiet "$BASE^{commit}" >/dev/null \
    || die "Base revision not found: $BASE"

# Determine the list of files to consider: explicit arguments, or every tracked
# file that differs from BASE in the working tree (staged + unstaged).
files=()
if [[ ${#args[@]} -gt 0 ]]; then
    files=("${args[@]}")
else
    while IFS= read -r -d '' f; do
        files+=("$f")
    done < <(git -C "$repo_root" diff -z --name-only --diff-filter=M "$BASE" --)
fi

[[ ${#files[@]} -gt 0 ]] || die "No changed files relative to $BASE."

# Single scratch directory, cleaned up on any exit.
tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

emit() {
    echo "# phpatcher-ed v1"
    echo "# Generated by tools/changes-to-patch.sh from changes vs ${BASE}."

    local f new orig numstat emitted=0
    for f in "${files[@]}"; do
        [[ -z "$f" ]] && continue

        # Skip binary files (diff -e is meaningless for them).
        numstat="$(git -C "$repo_root" diff --numstat "$BASE" -- "$f" 2>/dev/null | head -n1 || true)"
        if [[ "$numstat" == "-"$'\t'"-"* ]]; then
            echo "  skip (binary): $f" >&2
            continue
        fi

        new="$repo_root/$f"
        if [[ ! -f "$new" ]]; then
            echo "  skip (missing/deleted): $f" >&2
            continue
        fi

        orig="$tmpdir/orig"
        # A previously untracked file has no base version -> empty original.
        git -C "$repo_root" show "$BASE:$f" >"$orig" 2>/dev/null || : >"$orig"

        if diff -q "$orig" "$new" >/dev/null 2>&1; then
            continue
        fi

        echo "# file: $f"
        # `diff -e` exits 1 when files differ — expected here, not an error.
        diff -e "$orig" "$new" || true
        emitted=$((emitted + 1))
    done

    [[ "$emitted" -gt 0 ]] || die "Nothing to patch: no applicable changes found."
}

if [[ -n "$OUT" ]]; then
    emit >"$OUT"
    echo "Wrote $OUT" >&2
else
    emit
fi
